Refactor VISS_Sample_Data.R script
uw-ssec/biodiversity-horizons pull request #24
Opened 2024-11-12 06:56 UTC by IshikaKhandelwal

- Modularized key functions (`prepare_range, extract_climate_data, get_niche_limits, exposure, exposure_times`) and moved them to the `/R` folder for better code reuse and maintainability.

- Created a comprehensive driver script `scripts/VISS_Sample_Data.R `to orchestrate the workflow, including range preparation, climate data extraction, thermal niche limit computation, exposure calculation, and exposure times analysis.

2024-11-18 00:53 UTC, carlosgjs requested changes
this looks really good, mostly need to address the warnings and I have the question about exporting the core functions.

2024-11-18 00:53 UTC, carlosgjs commented on NAMESPACE
> +importFrom(dplyr,across)
shouldn't we be also exporting the main package functions here? E.g. `exposure`, `exposure_times`, etc?

2024-11-18 00:53 UTC, carlosgjs commented on R/exposure_times.R
> +exposure_times <- function(data, original.state, consecutive.elements) {
Can you look into all these warnings?

2024-11-21 17:32 UTC, IshikaKhandelwal commented
I am currently facing an issue where no linting warnings appear when I test the package locally using `lintr::lint_package()` and after applying fixes like `usethis::use_import_from()`, adding proper imports in @importFrom directives, and ensuring the namespace is updated.

However, when I push the changes to GitHub, the CI workflow still reports linting warnings, particularly related to missing global function definitions (e.g., %>%, tibble, pull). Despite matching the local linter configuration to the one used in GitHub Actions, I am unable to reproduce these warnings locally, making it challenging to debug effectively.

Any insights on what might be causing this discrepancy or suggestions on how to proceed would be greatly appreciated!

Thanks!

2024-11-26 19:23 UTC, IshikaKhandelwal commented
Added issue for tracking the warnings issue here: https://github.com/uw-ssec/biodiversity-horizons/issues/38

2024-11-27 01:22 UTC, carlosgjs approved these changes
The warnings will be addressed in https://github.com/uw-ssec/biodiversity-horizons/issues/38

2024-11-27 19:04 UTC, merged

2025-03-12 23:08 UTC, atambay37 commented
Closes #53 and #56